### ISSUE TITLE
Unable to parse json bytes containing WrappedMessage

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/protostream#379]
Reading JSON bytes will fail if the original Protobuf bytes contain a WrappedMessage.

```java
var bytes = ProtobufUtil.toWrappedByteArray(ctx, new WrappedMessage(1), 512);
var json = ProtobufUtil.toCanonicalJSON(ctx, bytes);
var jsonBytes = ProtobufUtil.fromCanonicalJSON(ctx, new StringReader(json));
```
Throws:

```java
java.lang.IllegalStateException: The field '_value' was not found in the Protobuf schema
	at org.infinispan.protostream.impl.JsonUtils.processObject(JsonUtils.java:256)
	at org.infinispan.protostream.impl.JsonUtils.processDocument(JsonUtils.java:150)
	at org.infinispan.protostream.impl.JsonUtils.fromCanonicalJSON(JsonUtils.java:89)
	at org.infinispan.protostream.ProtobufUtil.fromCanonicalJSON(ProtobufUtil.java:196)
```

**Comment by ryanemerson** [comment]
It appears that the root cause of the issue is that the original JSON representation for a WrappedMessage does not contain sufficient information for the object to be recreated and will actually produce an invalid JSON object if the message contained within `WrappedMessage` consists of multiple fields.

For example, `WrappedMessage(UUID)` will result in the following invalid JSON being generated:

```json
{"_type":"org.infinispan.protostream.WrappedMessage","_value":1005,"_value":"GdJNvZMpmrhJIVsBI+w5SN6O"}
```
